### ISSUE TITLE
Transcription and Encoding

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls#12]
The tasks in this issue (upon completion) will count as credit for Project Development for weeks ending  10/30, 11/6, and 11/13. 

I would like each of you @spadafour @rCarls @CodyKarch @KariWomack to read one article from the PDF images of the original articles (published in the Chicago Times) and try your hand at transcribing it. 

Go [here on GitHub](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_XML/ChTimes_TEIheaderANDstructureTemplate.xml) and download the TEI header and Structure Template by viewing the "raw" text, right-clicking and downloading/saving the file. 
Then, in oXygen, open that file. 
Review the TEI Header and edit the portions of the header (`<date>` inside of `<title>`... etc.) that describe the individual article you are working with and the `<resp>` element to specify that you are the one transcribing and coding the article. 
Once you have reviewed and edited the TEI header go down to the second `<div>` that is marked `@type="headlines"` and  transcribe each of the headlines into an `<item>` element inside of the `<list>` element.  
The main text of the article will be transcribed in the third `<div>` that is marked `@type="articleBody"`. Be sure to separate the text into `<p>` elements every time there is a paragraph break. However, do not be concerned with the page breaks because the poor quality of the images makes it difficult to tell when the pages are actually separated. 
Note: if there is no advertisement following the article (that references the series) delete or comment out the final `<div>` element that is marked `@type="advertisement"`.

As you are transcribing if you run into an area where the text is unclear and you can only infer what the text says or if the text is completely unreadable refer to our [codeBook](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/webDevelopment/codeBook.xml) on how to properly represent the unclear text.

Refer to [this article](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_XML/1888-07-30-ChTimes.xml) and our conversation in Issue #6  while encoding to see the kinds of elements, attributes, and attribute values we are using to encode the articles. If you decide there is something you want to encode that we have not already determined a TEI element for feel free to find an appropriate element in the [TEI guidelines](http://www.tei-c.org/Guidelines/). If you do this please leave a comment directly after the new element (inside of your XML) and ping the group in **this issue** with the element and your reasoning behind choosing it. 

Mark with comments (that include your name and date) areas of interest and parts of the article that stand out to you or that you have difficulty transcribing/encoding. 

When you are finished, push your transcription to the [ChicagoTimes_CSG_XML Folder](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/ChicagoTimes_CSG_XML) using your desktop client. 

Once you have completed your transcription and basic encoding (not an easy task so give yourself sufficient time) go into the [Anon_WSG Folder](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/Anon_WSG) and hunt for the corresponding [Barkley Section](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/Anon_WSG/BarkleyCollection) to the article you just transcribed. The best way to do this is by skimming the headlines of the sections in search of headlines that match those from your article. Read the section or sections (once you find whichever matches your article) and jot down any noticeable differences between the text and headlines of the Barkley section and the article you just encoded/transcribed. 

In the future, we will also want to do a similar review of the McEnnis chapters to see where in that text your article is referenced and how it differs from the original article. --- We can't do this just yet because we still need to go through the McEnnis text and transfer it into TEI XML. 

Upon completion of these tasks comment in Issue #9 giving us which section from the Barkley text a.k.a. [Anon_WSG folder](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/Anon_WSG/BarkleyCollection) corresponds with the article you transcribed and what the noticeable differences are between the texts/headlines. 

This is significant project work helping transcribe, begin basic TEI structure tagging, and the beginning stages of version comparing. This will also give each of you a chance to become better associated with the Nelson project and begin the process of finding interesting things each of you may want to produce data visualizations on for upcoming assignments.

Article Assignments:
@spadafour --- [8/6/1888](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_PDFandOldXML/Nell_Nelson_8-6-1888.pdf)
@rCarls --- [8/7/1888](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_PDFandOldXML/Nell_Nelson_8-7-1888.pdf)
@CodyKarch --- [8/8/1888](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_PDFandOldXML/Nell_Nelson_8-8-1888.pdf)
@KariWomack --- [8/9/1888](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_PDFandOldXML/Nell_Nelson_8-9-1888.pdf)

(It may be easier to view the PDF images of the files through our [source site found on the NYU Digital Library](http://dlib.nyu.edu/undercover/city-slave-girls-nell-nelson-chicago-times-aka-white-slave-girls-new-york-world). Simply find your article in the list of articles, click on it, and then click to view the PDF file.)

Please contact me via email or in this issue with any questions and concerns as they occur. 
Thank you!

**Comment by CodyKarch** [comment]
So, @RJP43 , I ran into a big problem with this... I went to Cassell to finish the transcription and corresponding Barkley section, but they had locked it up. I thought I would be finished this evening, but due to zero access to what I had nearly finished, I won't be able to due it for tomorrow.. What will we do?

**Comment by RJP43** [comment]
you could add your bio here in tics... like @spadafour did above

**Comment by CodyKarch** [comment]
sure.

**Comment by CodyKarch** [comment]
`Cody Karch is a student at the <a href="http://www.greensburg.pitt.edu/">University of Pittsburgh at Greensburg</a>, with plans to transfer to the main campus. His major is English Writing, but will be going into a duel-major in that and Philosophy eventually. Pitt-Greensburg's <a href="http://www.pitt.edu/~ebb8/DHDS/Fall2014-DHSyll.html">Digital Humanities Class</a> is what got him involved with this project. He is helping to transcribe, and support the formation of Nell Nelson project alongside others.`

**Comment by RJP43** [comment]
When you push your transcription to GitHub it should be in the [ChicagoTimes_CSG_XML](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/ChicagoTimes_CSG_XML) so there shouldn't be anything involved with the Barkley Collection besides looking at those files to determine differences with the file you transcribed and making a determination as of what section matches up with the article you transcribed.

**Comment by CodyKarch** [comment]
I know that, but like I'm saying, I literally can't finish it due to being locked out of Cassell
