### ISSUE TITLE
12-1 Class Meeting

### ISSUE THREAD

**Issue by spadafour** [RJP43/CitySlaveGirls#14]
@RJP43  accomplished:
* Added `<p>` tags to 7/30 and 7/31 (this article is incomplete)
* Proofread 7/30 and 7/31
* Added `<persName> <placeName> <orgName> <placeName type="address">`
* Fixed all of the `<unclear>` -- now consistent with TEI (for 7/30 and 7/31)

Needs to add:
* @spadafour add schematron to web development folder and fix 8/02 and /03
* @RJP43 adding dialogue tags for 7/30 and /31 (and finishing 7/31)
* @CodyKarch do CSS for entire site and article 08/08
* @KariWomack do articles 08/04 and /09

For fixing the assigned articles:
* Use [7/30](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_XML/1888-07-30-ChTimes.xml) as an example
* Place `<p> <persName> <placeName> <orgName> <placeName type="address">` tags
* Make an attempt to clarify `<unclear>` tags (refer to the [codebook](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/webDevelopment/codeBook.xml) for this)

Some notes:
* For exposed companies: `<orgName type="exposedCompany">` (Just grab the name, no pseudo-markup)
* While you are working, add references for both cities and company names and company addresses,do that by adding `@ref`: example: `<orgName type="exposedCompany" ref="#WLMC">Western Lace Manufacturing Company</orgName>`

**Comment by CodyKarch** [comment]
Just so y'all know, I basically finished changing the whole C.S.S. --who knew it would take one good evening? Anyway, I will show it to you in(or after) class Friday.

**Comment by ebeshero** [comment]
@CodyKarch Yay! But why keep us in suspense? Could you take some current pages and save them with a slightly altered file name (like add "tester" to the end of the name) and put them up in the newtfire space? That way the team can give it some thought and you all can discuss the new look when you meet on Friday!

**Comment by RJP43** [comment]
@CodyKarch yes go ahead and post it. Remember, I copied all of the files at the beginning of the week so that we can completely change everything without a worry that we don't have backups. So no fear if you save over something or like Dr. B. said name it tester and apply it to some or all of the pages and label it tester too ... whatever works for you to get it up for us to see  :) great job!

**Comment by RJP43** [comment]
`<p>"<said who="workingGirl" select="female" ana="wageDesc" corresp="negative">Then I must pay 10 cents car fare each time, and that leaves only 40 cents. I had to pay $3 before I could get any work. I always knew how to crochet, but they made me pay $2 for lessons and $1 as a security. I began in January, the first week, and now I am through. I have made $15, and when they give me back the dollar I shall have $16.</said>" <said who="nellNelson" select="female" ana="wageDesc" corresp="negative" aloud="false">Here is a company paying a girl of 18 $15 for six months and one week's labor</said>.</p>`  
                   ` <p>When <persName>Mr. Ford</persName> came from the work-room he was met by a boy who had brought in some work and was in a hurry to be off.</p>`  
                    `<p>"<said who="messenger" select="male"><persName>Mrs. Clark</persName> sent these mats and she, wants you to receipt for them.</said>"</p>`

Okay so this is how I have started handling dialogue and quotes. @ebeshero I am almost certain that I am not using some of these attributes as the TEI intended and I am wondering how we can go about fixing this while still binding all of this information together. Let me explain what I have each of the attributes meaning 

`@who` -- for this I am indicating who the person is speaking between a few selections `workingGirl | foreman | forewoman | messenger | nellNelson | unidentified` We could add to these as it becomes necessary, but only once the group has discussed the necessity.    
`@select` -- here I am identifying the gender/sex of the speaker  with values of  `male | female | unknown`  
`@ana` -- with this I am trying to indicate the subject matter being discussed with these few selections `wageDesc (any conversation discussing wages) | livingCond (any conversation discussing how a person's living conditions are) | workEnvir (any conversation discussing the physical/literal environment being worked in) | workDesc (any conversation describing the work being done)` We could add to these as it becomes necessary, but only once the group has discussed the necessity.   
`@corresp` -- then this attribute determines if the connotation in the `@ana` description is being discussed in a `positive | negative | neutral` manner  
`@aloud` -- finally this I am using for the comments that Nelson makes as obvious assertions to the reader but are not spoken aloud ... we will assume the other quotes are spoen aloud unless specifed with this attribute and the corresponding `false` value. ex = `aloud="false"`

**Comment by RJP43** [comment]
Here would be a conversation when there aren't real specifics being discussed   
`<p>"<said who="workingGirl" select="female">I brought the mate back.</said>"</p>`  
                    `<p>"<said who="foreman" select="male">Oh, you have, eh?</said>" opening a piece of newspaper and unfolding a dozen hand-made mats the size of a tea-plate. The work is carefully examined on both sides and as he proceeds the scowl deepens. Without a word he tosses the lot on the little table and reaches for the proffered blank the girl had opened.</p>`  
                   `<p>"<said who="foreman" select="male">What's your name?</said>"</p>`  
                    `<p>"<said who="workingGirl" select="female"><persName>Rhafferty</persName>.</said>"</p>`  
                   `<p>"<said who="foreman" select="male">How do you spell it?</said>"</p>`  
                    `<p>"<said who="workingGirl" select="female">R-h-a-f-f-e-r-t-y.</said>"</p>`  
                    `<p>"<said who="foreman" select="male">Oh, yes; <persName>Martha Rhafferty</persName>,</said>" after hunting through a long list.</p>`  
                    `<p>"<said who="foreman" select="male">Do you want more work?</said>"</p>`  
                    `<p>"<said who="workingGirl" select="female">No, sir.</said>"</p>`  
                    `<p>"<said who="foreman" select="male">There's plenty more if you want it.</said>"</p>`  
                    `<p>"<said who="workingGirl" select="female">No; my mother don't want me to do any more crocheting.</said>"</p>`  
                    `<p>"<said who="foreman" select="male">Well, <persName>Mr. White</persName>
        isn't in now. Can't you come in again?</said>"</p>`  
                    `<p>No answer. A look of discouragement comes over the young face.</p>`  
                    `<p>"<said who="foreman" select="male">Don't you have to do any shopping about town?</said>"</p>`  
                    `<p>"<said who="workingGirl" select="female">No, sir.</said>"</p>`  
                    `<p>"<said who="foreman" select="male">Well, you can wait, can't you? Wait here. Take a chair.</said> (I had the only one.) <said who="foreman" select="male">Just go in the next room there and take a chair.</said>"</p>`

**Comment by ebeshero** [comment]
@spadafour @CodyKarch @KariWomack @RJP43 Becca and I are talking about this now, and came to a decision: It's not technically right with the TEI (they have a harsh phrase on the Tech Council called "tag abuse") to use `@corresp` in that way. So it's best to nest a couple of elements for the specific use-cases you are thinking about here. Try nesting like this:

````
<said who="nellNelson" ana="female"><rs type="wageDesc" subtype="negative">quote goes in here</rs></said>

````

Will that work?

**Comment by KariWomack** [comment]
Hey, guys. I trying to get my work done for tomorrow, but my desktop GitHub isn't loading. I'll keep trying to reload it and maybe let it go for a bit before trying again, but hopefully it will be working by tonight/tomorrow so I have stuff done Friday. If not, maybe I can work it out on a lab computer or have someone look at it tomorrow. Just letting you guys know im trying here. See you tomorrow!
