### ISSUE TITLE
xml:ids for Companies to correlate Companies and Addresses

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls#15]
Here are a few example of how your `<orgName>` and `<placeName type="address">` should be coded using the `@ref` attribute. The `@ref` attribute that will correspond to an xml:id in our Site Index. In this issue please list any companies that you identify in your articles with the corresponding xml:id you chose for the company and refer to this issue before assigning new xml:ids to be sure no one else has already come across the company and given it an xml:id.  Thanks everyone @KariWomack @CodyKarch @spadafour !!

This is how the code looks with text sitting around the coded information ... this is an example of  how we code company names as well as the corresponding addresses:
`The fifth place on my list was the "<orgName ref="#WLMC" type="exposedCompany">Western Lace Manufacturing Co.</orgName>" <placeName ref="#WLMC" type="address">218 State street</placeName>`    

The following do not have the surrounding text so as to simplify the examples:  
  
This is an example of how you put a ref id on an orgName that isn't specified as a company:
`<orgName ref="#WPA">Woman's Protective agency</orgName>`  
  
This is an example of how you put a ref id on an orgName that is specified as a company but sits separately from the given address:
`<orgName ref="#RCRB" type="exposedCompany">Rosenthal &amp; Co.'s and Rosenberg Bros</orgName>`  
  
This is an example of how you put a ref id on an orgName that is specified as a company and sits with a partial address:
`<orgName ref="#Stein" type="exposedCompany">Stein's</orgName>, on <placeName ref="#Stein" type="location">Market street</placeName>`

**Comment by RJP43** [comment]
The companies identified in [article 1888-07-30-ChTimes](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_XML/1888-07-30-ChTimes.xml):  
  
`#WLMC` - Western Lace Manufacturing Co.  
`#WPA` - Woman's Protective agency  
`#RCRB` - Rosenthal &amp; Co.'s and Rosenberg Bros  
`#Stein` - Stein's  
`#Ludden` - Ludden's  
`#NRJC` - Never-Rip Jersey Company  
`#MarshF` - Marshall Field's  
`#Ellinger` - Ellinger's

**Comment by KariWomack** [comment]
Companies from 8-9-1888:
#Gold - Goldsmith's
#Olson - Olson's
#KNels - Knute Nelson's
#BS - Benson's Shop
#Schmall - Schmallen's

**Comment by spadafour** [comment]
Forgot to add mine, I only had one:
`#EUC` - Excelsior Underwear Company

**Comment by CodyKarch** [comment]
Question: what if we aren't sure whether the name of the business is "Boston store" or if that is the place described?
`For <rs type="workDesc|workEnvir" subtype="negative" resp="CAK">dismal surroundings, economy of comforts, and heartless treatment</rs>, to the Boston store belongs the palm.`

**Comment by RJP43** [comment]
hmm... @CodyKarch  I can't really tell by this context so just comment tag it and we can tackle it as a group tomorrow

**Comment by RJP43** [comment]
@CodyKarch also i would only give that a rs type of workEnvir because workDesc should be reserved for actual description of work being done and this sounds like only a description of environment ... see issue #17 for detail description of each value

**Comment by CodyKarch** [comment]
Yeah, I caught that on my own too, good job noticing my error!

**Comment by RJP43** [comment]
The companies identified in [Article 1888-07-31-ChTimes](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_XML/1888-07-31-ChTimes.xml)

`#Ellinger` - Ellinger's  (repeat)
`#Willong` - Willonghby, Hill &amp; Co.  
`#WPA` - Woman's Protective agency (repeat)

**Comment by RJP43** [comment]
can everyone please put your personal xml:ids here:

for example mine is `#rjp`

**Comment by KariWomack** [comment]
#KMW

**Comment by RJP43** [comment]
The companies identified in [Article 1888-08-19-CHTimes](https://github.com/RJP43/CitySlaveGirls/blob/master/ChicagoTimes_CSG_XML/1888-08-19-ChTimes.xml):

EXPOSED COMPANIES:
`#HSC` - H. Schultz &amp; Co.'s paper-box manufactory
`#KBO` - trousers manufactory of K. B. Oleson
`#Doremus` - Doremus laundry
`#Loomis` - Loomis laundry
`#Munger' - Munger laundry
`#OrienLaun` - Oriental laundry owned by E. Jennings

OTHER ORGANIZATIONS:
not sure if going to mark this or give it ID? - custom shop on the fourth floor of S. Nelson's building
`#` give it ID? - the board of trade
`#` give it ID? - the Corn Exchange bank
 


`
