### ISSUE TITLE
Consistent Coding

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls#17]
@KariWomack @CodyKarch @spadafour @ebeshero 

I am going to make a list here of the elements, attributes and values we should be using and the descriptions associated so that we are making sure to code consistently. @spadafour  This will also, hopefully, be useful in the writing of the schematron. Everyone please refer to Issue #15 for the xml:ids of the companies so that we also keep those consistent between articles and be sure to add to that issue when you encounter companies you have to make an xml:id for if it isn't listed there already. 

the **structural elements** are `<head>`, `<div>`, and `<p>`
* the `<head>`element contains the element `<title>` only
* the `<div>` element has the attribute `@type` which is equal to one of the following values `"headlines"`, `"articeBody"`, or `"advertisement"`
*inside of the `<div type="headlines">` there is the additional structural markup of `<list>` and `<item>` with each `<item>` holding the individual headline sentences. There are no `<p>` elements inside of this `<div>`.
* the other two div types should have `<p>` elements separating the paragraphs as they are represented in the original texts.

**contextual markup:**  
the `<date>` element should always have the `@when` attribute and the value associated should always follow the year-month-day format for example `<date when="1888-07-31">`

the `<orgName>` element just needs the `@ref` attribute with corresponding value associated to the specific organization (list of these xml:ids are in Issue #15) when used with any organization that is not a company being discussed by Nelson or a working girl. 
When it is such a company you add the attribute `type="exposedCompany"` in addition to having the `@ref` attribute with the corresponding value associated to the specific company (list of these xml:ids are in Issue #15).

the `<persName>` element is going to surround any person's name whether it is just a first name, nickname, last name, or full name reference. Although we are not using this element specifically his semester for data analysis this is information that might be needed in the future. 

the `<placeName>` element can be left without any attribute when used for the name of a place generally for example around the name of a city or country otherwise we add the attribute `@type` and the associated value `"address"` and when used in reference to the exact address of a company we add the `@ref` attribute and corresponding value associated to the specific company (list of these xml:ids are in Issue #15).

the `<said>` element gets the attributes `@who` and `@ana`
* `@who` can equal any of these values: `"unidentified"`, `"workingGirl"`, `"nellNelson"`, `"foreperson"`, `"employer"` (employer references the owner of the company only be careful not to confuse this with a foreman there is a distinction), `"employee"` (referring to any employee that is not at the same level of labor as the working girls for example a clerk or secretary), `"benefactor"` (this is used in the instance in once specific article where a man gives Nell carfare but does so with ill intentions and this is the name used for that man by Nelson so we can hold onto that), and finally `"messenger"` (this will be for  any person that is speaking on behalf of someone else and we frequently see this with relations of working girls like a mother or son coming into the company inquiring about work or informing of illness and Nelson documents the dialogue had between the messenger and the employer or foreperson)
* `@ana` can have the following associated values `"unknown"`, `"female"`, or `"male"`

the `<rs>` element can have the attributes `@type`, `@subtype`, and `@resp`
* `@resp` includes the `#` and the xml:id of the interpreter
* `@type` can have the following values `"interruption"` (used as an indicator when Nelson interferes some kind of dialogue with journalistic additives for example he the told me or she cried  appearing in between quoted material), `"wageDesc"` (any conversation discussing wages), `"livingCond"` (any conversation discussing how a person's living conditions are), `"workEnvir"` (any conversation discussing the physical environment being worked in), `"workDesc"` (any conversation describing the work being done), `"wgDesc"` (description of a working girl individually or group of working girls for example the following two sentences would get that `@type` : "Her face was sad and so very, very pale that I shall never look at a jersey again without seeing her face." and "The average age may have been 23, but not less. There were girls of 17 and 18 and some world-weary women past 50 all working for little more than enough to keep body and soul together."), and `"personDesc"` (description of an individual that is not a working girl).
* `@subtype` can have the following values `"postive"`, `"negative"`, or `"mixed"` (explained in Issue #16)

HOPE THIS HELPS!

**Comment by spadafour** [comment]
I think we should add one more `@type` for the `rs` element, something like `general`. The reason: the benefactor. When he speaks, he says some interesting things, which I can mark up as positive or negative, but he mostly isn't speaking specifically about living conditions or anything. @RJP43 what do you think?

**Comment by RJP43** [comment]
@spadafour @KariWomack @CodyKarch Okay so I am trying to finish up the XSLT for the article templates and I am getting started on writing the `<span>` representations for the `<rs>` and I am running into the question on whether we want to have our spans pull out the `@type` or `@subtype`... a basic question here... Do we want to have the conditions or the connotations be colored text? VERY BASICALLY  when the website user toggles the javascript there will be a sense of who is speaking identified one with CSS (underline, bold, a color, etc.) and then when they hit another toggle it will show what they are talking about (context) or what tone (positive or negative) they are talking about. There is also the option to use the title attribute on any html element and [tooltip](https://en.wikipedia.org/wiki/Tooltip), which we would need to research more if we want to have both the `@type` and `@subtype` appear in some way. 

Also another cool thing we can do perhaps even easier than an svg graph or perhaps alongside it would be to create an SVG bar of sorts at the top of each article that would give us a representation of how negative a single article by focusing on the `<rs>` `@subtype`. This idea was suggested by Dr. B. right after class and I could imagine we would take the count of instances where the `@subtype="negative" and set it in relation to the total `@subtype`s to determine how negative a single article is...

what does everyone think about all of this?

**Comment by RJP43** [comment]
Only XML to tag as of 12/11 until we get the schematron and site index complete  

the **structural elements** are `<head>`, `<div>`, and `<p>`
* the `<head>`element contains the element `<title>` only
* the `<div>` element has the attribute `@type` which is equal to one of the following values `"headlines"`, `"articeBody"`, or `"advertisement"`
*inside of the `<div type="headlines">` there is the additional structural markup of `<list>` and `<item>` with each `<item>` holding the individual headline sentences. There are no `<p>` elements inside of this `<div>`. (no contextual markup in headlines, please! It causes duplicate information.)
* the other two div types should have `<p>` elements separating the paragraphs as they are represented in the original texts.

**contextual markup:**  
`<orgName type="exposedCompany" ref="#theXMLid>` (XML identified in #15)> 
`<said>` for quoted info. 
`<placeName type="address" ref="#theXMLid>` (XML identified in #15)
more generally `<orgName>` and `<placeName>` tags
