### ISSUE TITLE
Rules to Constrain with Schematron: 

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls#21]
Rules to Constrain with Schematron:  
`<said>`  -  and corresponding `@who` with the values of  "unidentified", "workingGirl", "nellNelson", "foreperson", "employer"  "employee" "benefactor" "messenger" and `@ana` with the values "male", "female" "unknown" 

... add more here with questions ...

**Comment by spadafour** [comment]
Hey @ebeshero I'm starting to work on my schematron. Is there anything special I need to do with the header?

**Comment by RJP43** [comment]
@spadafour I will have the site index done by this evening just to touch base with you... I will ping you wheb it's complete and synced

**Comment by spadafour** [comment]
Cool! Thanks. I only have a couple hours before I have to leave for work, but I'll try and get this done.

**Comment by spadafour** [comment]
Hey, I'm having an issue associating my schema with the document. I'm clicking on validate > validate with... > finding my schematron (and making sure that the correct schema type is selected). Nothing seems to appear in my header, and its not finding any of my changes. Is it because we already have an associated schema (the TEI one in the header)??

**Comment by spadafour** [comment]
It might have to do with my header in my schematron itself? Maybe? I jacked it from the schematron 1 homework:

`<schema xmlns:sch="http://purl.oclc.org/dsdl/schematron" queryBinding="xslt2"`
`    xmlns:sqf="http://www.schematron-quickfix.com/validator/process"`
`    xmlns="http://purl.oclc.org/dsdl/schematron">`

**Comment by spadafour** [comment]
Okay, I got it associated, I just have to make sure my rules are firing

**Comment by spadafour** [comment]
Okay, I spent a while trying to get a schematron working. I got the namespace to attach to a file, but I can't get any rules to fire. I need to leave for work, and I won't be home until around 11:30 tonight. @RJP43 can you take a look at it and see if you can find out what I'm doing wrong? It's not complete, but its a start. At least 3 of the rules SHOULD be right (they are at least properly written), but I can't figure out why the changes aren't being tracked. It's called nelsonSchematron and its filed under the Web Development folder.

**Comment by ebeshero** [comment]
@spadafour @RJP43 I bet I know what the problem is: It'll be a namespace issue with the TEI...I may be able to quickly correct it from here if that's the case. I'll take a look in a minute.

**Comment by ebeshero** [comment]
@spadafour @RJP43 I repaired the Schematron problem: you just need a `tei:` prefix in front of every element name. (And you don't need or want them for attribute names, which are in their own parallel universe namespace). So, for example, if you wanted to test for something in all the placeName elements inside the body element, you write your patttern rule like this:

````
 <pattern>
        <rule context="tei:body/tei:placeName">
             <!-- rule assert/report stuff here -->
        </rule>
</pattern>
````

Two New Things:
1) I left a big block of comments in the file for help with reaching into the Site Index file once Becca has it ready.  It contains some sample code from the Amadis project that we can work on adapting.

2) I associated this Schematron (and left the schema lines in) two of your article XML files for Chicago Times articles: 1888-07-30 and 1888-08-03, so those will show up as changed in your ChicagoTimes_CSG_XML directory.

Hope that helps!

**Comment by ebeshero** [comment]
By the way, great debugging work, @spadafour, in tracking down the problem. You were pretty close, I think, to finding the solution yourself!

**Comment by RJP43** [comment]
@ebeshero and @spadafour  I finished the main important structure of the [site index](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/webDevelopment/siteIndex.xml). There are some things to add. For one we still need to put the McEnnis `<listBibl>` in and all the corresponding chapters insides of `<bibl>` elements. Another thing we need to do is add descriptor notes to each of the `<nym>` elements  inside of the `<listNym>`. @ebeshero can you let us know if I did this right and whether or not it i enough for @spadafour to work with for the [schematron](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/webDevelopment/nelsonSchematron.sch). Thanks!

**Comment by ebeshero** [comment]
@RJP43 @spadafour I've just added some comments to your site index and pushed it to the repo. Yes, this is fine for Rob to work with for the Schematron: Think about where you want this to sit in your file directory: Usually I store the project schematron in the same place with the site index and it's typically an outer directory.

**Comment by ebeshero** [comment]
@RJP43 Becca, you just want to rethink how you're representing newspaper articles: See my explanation of the @level attribute on `<title>` and consider that you need to represent the title of the newspaper in the `<bibl>` entries. I left a big comment on how to do that in your siteIndex file.
