### ISSUE TITLE
Today's Meeting - 12/14

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls#22]
@CodyKarch @spadafour: @KariWomack and I are in the classroom so whenever you guys can get here this is where we will be until we (possibly) get booted ! We can record what is accomplished today and tasks to move forward in this issue!

**Comment by RJP43** [comment]
next meeting at 10AM on Wednesday 12/16 @CodyKarch @spadafour @KariWomack come with articles finished if possible and whether finished or not please SYNC and ping us by Tuesday night by 7pm so we can swarm and help you finish!

**Comment by RJP43** [comment]
okay so what we accomplished at this meeting: 

## A few decisions made in regards to markup -     
1. we decided to eliminate all of the `<rs>`tagging except for the `<rs type="interruption">`   
2. for the `@ana` associated with `<w type="noun">`  and the `@who` on the `<said>` elements there should be a reference `#` preceding the following options `"nellNelson" "workingGirl" "foreperson" "employer" "employee" "benefactor" "messenger" "unidentified"` to link back to the site index  
3. if you have an adjective modifying another adjective tag those together as a single adjective same with hyphenated adjectives.  
For example `the <seg><w type="adj" ana="pale-faced">pale-faced</w> <w type="noun" ana="#workingGirl">girl</noun></seg>` OR `<seg><w type="adj" ana="far">very far</w> <w type="noun">distance</noun></seg>`  

## Accomplishments:  
 @spadafour @ebeshero and I fixed the schematron to constrain a majority of the tagging we are doing ( @spadafour I added on some note within the past hour of a few additional rules we need to add, but we can tackle those together on Wednesday or have a look at them whenever you get a free moment ). We went ahead and edited the site index and the `<teiHeader>` elements for all of the XML files of articles we have transcribed to remove duplicate information and so that the schema is associated. @KariWomack worked diligently to complete one full article and make progress on her second article fixing the mark-up to add grammatical markup. 

**Because of the change in all of the files' `<teiHeader>` elements it is very important that you SYNC before you begin working on your files and adding/removing markup!!!**

# NEED TO DO

* by next meeting have all articles' markup fixed  
* edit the schematron to add those couple of rules commented out at the bottom and mentioned above  
* edit the site index to add information to each of the `<nym>` inside of the `<listNym>` section (this is regarding the archetype / canonical references)  
* repair XSLT to transform XML articles into HTML to add to the website and then transform all of the articles  
* determine what out SVG will be (some how graphing specific nouns and adjective uses is likely)  
*  @RJP43 will need to edit methodology and do comparative tagging with @spadafour [version of article 8/2/1888 with old ethnographic markup using the other `<rs>` elements](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ResearchDevelopment/1888-08-02-ChTimes-spadaforeComparison.xml)  as example of issue in old tag systems  
* complete overview and edit of the site to remove some information, organize previous markup, and incorporate the new article HTML pages with `<span>` elements and `@class` attributes that  need added to the CSS and possible/likely javaScript

**Comment by CodyKarch** [comment]
Question: How do we approach adjectives written out as numbers? Do we simply act like it is a normal adjective, just written in numerals?
Like: `<w type="adj" ana="hundred">100</w>`

**Comment by CodyKarch** [comment]
Question2: How do we approach words that were mistyped and we provided a correct version of? Would it be like thus?
`<choice><sic><w type="noun">beeeze</w></sic><reg resp="CAK"><w type="noun">breeze</w></reg></choice>`
or
`<choice><sic>beeeze</sic><reg resp="CAK"><w type="noun">breeze</w></reg></choice>`

**Comment by CodyKarch** [comment]
Question3: What would the ana attribute of the adjective "sizzling" be? I assume "sizzle".

**Comment by CodyKarch** [comment]
Question4: How do I manage this? `at the extreme south-east corner of the floor`
Would it be marked up as `at the <seg><w type="adj" ana="extreme">extreme</w><w type="adj" ana="south-east">south-east</w><w type="adj" ana="corner">corner</w> of the <w type="noun">floor</w>`

**Comment by RJP43** [comment]
Hey everyone I am on my way to campus running a little late, but I will see you all soon.
