### ISSUE TITLE
Finished Website... EXCEPT...

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls#28]
Hi everyone ( @spadafour @KariWomack @CodyKarch @ghbondar @ebeshero ), 

Alright so the site is finally finished.... EXCEPT........ 

there are a few problems I am having once I transferred the site to the web that I'm confused on and looking for help. Everything is synced! 

Okay, first thing when I open the index page locally it looks like how I want it to, like this:

![capture](https://cloud.githubusercontent.com/assets/8645521/11920518/26c175e2-a740-11e5-9ecf-d54cf06746f6.JPG)

but when I open it on [the webpage](http://nelson.newtfire.org/index.html) the second image doesn't appear (except for on my phone... curious I know!)

Okay, second thing is that the SSIs aren't working only on  the article HTML pages (these pages were generated using [this XSLT](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/Website2015/webDevelopment/articleXMLtoHTML.xsl) if that helps) and this is the error I am getting:

![ssiissue](https://cloud.githubusercontent.com/assets/8645521/11920464/a1cee6c2-a73e-11e5-83c9-6f5042cf606a.JPG)

it starts at the top of the page and the second line finishes after the article text. And yes I opened the HTMLs and checked if they were valid in oXygen.

I'm tagging @amielnicki and @nlottig94  as well just in case either of them get a chance to look at this and can help

**Comment by ebeshero** [comment]
@RJP43 I'm looking at it now: 
1) On the index.html page (viewing in Chrome), I *am* seeing two images, side by side. The one on the left is the picture of Nell you've had up all along, and the one on the right is an ad for *The White Slaves*. Both images are captioned. Is that what I'm supposed to be seeing?

2) I see the SSI error, and I'm just now syncing my GitHub to take a look. My first thought (before investigating your file hierarchy) is the problem could be your referencing of top.html, in relation to the article file...but I need to take a closer look.

**Comment by RJP43** [comment]
@ebeshero interesting it must be my chrome browser.... I can see both images using explorer.

**Comment by ebeshero** [comment]
@RJP43 YES--indeed that *is* the problem: In your SSI line, you are referencing top.html as if it is sitting in a parent directory in relation to the articles. But when I look at your files on newtfire, top.html is sitting on the same directory level with each article file. Fix that and I think you'll be good.

**Comment by RJP43** [comment]
AHHHHH.... ok thanks.

**Comment by ebeshero** [comment]
By the way, the article interface looks great (so far--I haven't seen it with the SSI yet) Check your spacing on the About page for the project team listing. You probably want a space or some padding after the role name and the text following: (Editor:Name). The link to last year's clickable graph in Obdurodon takes the reader through a pretty dramatic color shift--actually kind of hurts the eyes to shift back. Can you incorporate that in your new CSS on your new site?

**Comment by RJP43** [comment]
yes I can and plan on it over break (there is a reminder to do so in the HTML), but this was all I had time to do. I have literally not stopped working on it for three days.

**Comment by RJP43** [comment]
I'm exhausted which also makes sense why I didn't catch the change for the include (all the articles were sitting inside of a separate folder called articles when I first  created the articles pages with the XSLT so there were a series of change I made and that was the one I passed over). Thanks again for catching that! I will see what I else I can fix when I get home from grabbing a bite to eat.

**Comment by ebeshero** [comment]
@RJP43 Don't worry about it--it doesn't affect anyone's grade--My eyes were just shocked by the color shift!

**Comment by RJP43** [comment]
Okay the SSI issues is fixed and Nasib fixed my chrome browser so I can see both images now :)

**Comment by RJP43** [comment]
Scratch that I changed the top and forgot to change the foot now ... so I will do that when I get back
