### ISSUE TITLE
Article Transcription -- Spring 2016

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls#29]
@nlottig94 

As you requested:

If you want to get started on an article I think a nice early one to begin that some how has been skipped over would be the article from 1888-08-01.  The following should be everything you need. Comment in this issue with any well issues .. lol 

The pdf of this article can be found on this repo. [here](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_PDFandOldXML/Nell_Nelson_8-1-1888.pdf) or you can view the article by going to it on the [NYU Site](http://dlib.nyu.edu/undercover/iii-city-slave-girls-nell-nelson-chicago-daily-times).  

Use [this template](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_XML/ChTimes_TEIheaderANDstructureTemplate.xml) to guide you for the TEI header and the general structural tagging format, but refer to [this finished article](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_XML/1888-07-30-ChTimes.xml) because there may be some mistakes in the template that have yet to be fixed since the drastic editing of the articles at the conclusion of last semester. 

This is the information from the site index that will be helpful in editing the TEI header 
`<bibl xml:id="CT003">
                  <title level="a">"City Slave Girls" <date when="1888-08-01"/></title>
                  <title level="s">Chicago Times</title>
                  <author>Nell Nelson</author>
                  <editor>Chapin, Charles</editor>
                  <edition>Newspaper Print</edition>
                  <extent>21-part series: Front-page placement</extent>
                  <publisher>Chicago Times</publisher>
                  <pubPlace>Chicago</pubPlace>
                  <date>1888</date>
                  <publisher>New York University Digital Library Technology Services (DLTS)</publisher>
                  <availability>
                     <p>
                        <ref target="http://dlib.nyu.edu/undercover/city-slave-girls-nell-nelson-chicago-times-aka-white-slave-girls-new-york-world">www.dlib.nyu.edu</ref>
                     </p>
                  </availability>
                  <note/>
               </bibl>` 
and the entire site index can be reviewed [here](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/webDevelopment/siteIndex.xml)  

if you have difficulty reading the pdf (you are not alone) and you can reference either Barkley Section 6 or 7 to see if you can find the missing text. I say 6 or 7 because we have yet to confirm if the article you will be working on is covered in both of these sections or just one of them. You can find the Barkley sections [here](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/Anon_WSG/BarkleyCollection). Please confirm for us when you find out what section(s) are associated.

Important to note if you cannot transcribe something due to the quality of the image or due to the newspaper print follow the guidelines in our code book for [damaged and unclear text](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/webDevelopment/codeBook.xml). Even if you refer to the Barkley text and get the correct text still put a damage and unclear tag around the provided text to inform us that the text provided is not directly transcribed from the pdf image. Also reference this codebook for irregular spellings and how we are handling those. These things are the first two (of the three) rules listed.

Don't worry about marking up grammar tagging; however, you can throw simple `<placeName>` tags around references to places, `<orgName>` tags around company or organization references, `<persName>` tags around specifically named people, and `<said>` tags around any **quoted** conversations. There will need to be some editing with those tags as they are very generic and we have a more complex system of attributes with those in place that I can explain better to in person or later in another issue. 

Thanks for wanting to be a part of this and @spadafour and I welcome you to the Nelson Team :)

**Comment by RJP43** [comment]
@nlottig94  also referring to issues #17 and #15 may be helpful but if the seem confusing don't worry I can explain things better once we are together. Also I forgot to mention use `<p>` tags to separate every paragraph if Nelson purposely begins a new paragraph even if for just one sentences it gets a new set of `<p>` tags. Hopefully this wasn't too much to scare you away ... lol !

**Comment by nlottig94** [comment]
@RJP43 So I have a piece of damaged paper here, but it almost looks like it was intentionally whited out...What attribute should I use for something like that?

**Comment by RJP43** [comment]
Could you use the snipping tool on your computer and paste an image of what you mean here in a comment? Can you make out any part of the word to figure out what is being said? And have you looked at the Barkley publication to see if the word is there? Call me if ya want.

**Comment by nlottig94** [comment]
Okay...I figured it out...apparently I was zoomed in too far!  It has been one of those days so far!   Sorry!

**Comment by RJP43** [comment]
Could you use the snipping tool on your computer and paste an image of what you mean here in a comment? Can you make out any part of the word to figure out what is being said? And have you looked at the Barkley publication to see if the word is there? Call me if ya want.

**Comment by RJP43** [comment]
Oh okay lol

**Comment by nlottig94** [comment]
Sorry!  I didn't know that was possible!

**Comment by RJP43** [comment]
Me either lol

**Comment by RJP43** [comment]
Hey also did you determine an xml:I'd for yourself yet and I will need a bio from you to add to the website... you can add that here if you like or we can do it together tomorrow night.

**Comment by nlottig94** [comment]
I have just been using `#nll` and I think I'll just wait for tomorrow night!!  If that's okay!

**Comment by RJP43** [comment]
That works :)

**Comment by nlottig94** [comment]
Okay!  One more thing, if she is quoting a sign, should I still wrap it in a `<said>` tag? Because it is in quotes.

**Comment by RJP43** [comment]
No put it in its own set of `<p>` tags and add a comment either before or after noting it is a sign. Also remind me to show you tomorrow night how we handle brief interruptions (like she said or he proclaimed) that come up in the middle of quoted text.

**Comment by nlottig94** [comment]
Okay.  Sounds good!

**Comment by nlottig94** [comment]
Okay, so the first part of the article (up to the headline of STARVATION WAGES.) is in Barkley Section 6.  The next part of the article starts on section 7.

**Comment by nlottig94** [comment]
@brookestewart Here is the information you need to transcribe and code the article.  I'll link what article in a couple minutes!

**Comment by nlottig94** [comment]
First, clone this repository.  Then navigate to [this article](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ChicagoTimes_CSG_PDFandOldXML/Nell_Nelson_8-10-1888.pdf).  This is the article from 08-10-1888 that also be found at the [NYU site here](http://dlib.nyu.edu/undercover/xii-city-slave-girls-nell-nelson-chicago-daily-times).  Refer to the corresponding [Barkley section 13](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/Anon_WSG/BarkleyCollection/BarkleyS13.xml) for reference when the text is hard to read.  Otherwise use the links above (article template, code book, and finished article) to get started.  Also, if you have names of people use the `<persName>` tag.  If you have any questions, just add a comment with the date and your initials within the xml!  Good luck!

**Comment by brookestewart** [comment]
Just making a note that it's actually Barkley section 15. I was so confused for awhile!

**Comment by nlottig94** [comment]
Whoops!!  Sorry!!!  I don't know what we were thinking!  Sorry!!

**Comment by RJP43** [comment]
Yea actually I think it is an error in the site index. Thanks for catching that!

**Comment by RJP43** [comment]
Or actually I had made the mistake of looking at the wrong site index entry ... which by the way here is the [site index](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/webDevelopment/siteIndex.xml) and this is your ( @brookestewart ) article's site index entry  
`<bibl xml:id="CT012">
                  <title level="a">"City Slave Girls" <date when="1888-08-10"/></title>
                  <title level="s">Chicago Times</title>
                  <author>Nell Nelson</author>
                  <editor>Chapin, Charles</editor>
                  <edition>Newspaper Print</edition>
                  <extent>21-part series: Front-page placement</extent>
                  <publisher>Chicago Times</publisher>
                  <pubPlace>Chicago</pubPlace>
                  <date>1888</date>
                  <publisher>New York University Digital Library Technology Services (DLTS)</publisher>
                  <availability>
                     <p>
                        <ref target="http://dlib.nyu.edu/undercover/city-slave-girls-nell-nelson-chicago-times-aka-white-slave-girls-new-york-world">www.dlib.nyu.edu</ref>
                     </p>
                  </availability>
                  <note/>
               </bibl>`

**Comment by brookestewart** [comment]
Thanks guys! @RJP43 @nlottig94

**Comment by brookestewart** [comment]
Are the $ okay to leave in the text? I wasn't sure if it was a reserved character.

**Comment by RJP43** [comment]
Yes they are fine

**Comment by RJP43** [comment]
And thank you!

**Comment by brookestewart** [comment]
I'm almost done transcribing! I only did some basic coding because I wasn't sure what all was included.

**Comment by brookestewart** [comment]
I'm pushing it to Github now! You may want to double check the TEI header and the tagging to make sure it's correct.

**Comment by brookestewart** [comment]
Okay, just kidding. It says I don't have permission to push to this repository.

**Comment by ebeshero** [comment]
Hi Brooke--I bet that Becca hasn't added you as a collaborator (yet)--but I wonder if this is a good opportunity to try issuing a contribution with a pull request? 

Dr. B, rushing about in prep for class...


Typeset by hand on my iPad

**Comment by RJP43** [comment]
Wow great fast work! I will add you as a collaborator now and you can push... sorry about that!

**Comment by RJP43** [comment]
Oooo yea great idea ... yes go ahead and try your hand at a pull request.

**Comment by RJP43** [comment]
You may have to fork the repo first. Report back or  if it stumps you the  let me know and I can add you as a collaborator.

**Comment by brookestewart** [comment]
Okay! I actually have to get ready and leave for class right now, but I'll try the pull request or forking when I get back home.

**Comment by brookestewart** [comment]
It seems I can't issue a pull request without forking the repository. I clicked fork and found my way to the forked repository, but I can't issue a request there either.

**Comment by RJP43** [comment]
Ok now that you have forked the repo using the online version and once you are on your online forked repo you then have to clone that "new repo" to your local machine ... then on the desktop client add the file to the CT XML folder, commit, and sync. Then there should be the option to do a pull request.  Thanks for experimenting with this! This kind of trial and error is what @ebeshero was talking about when she said we would have the returning students testing on the other functions of GitHub :)

**Comment by RJP43** [comment]
If you feel extra ambitious you can add a branch within your fork (from the Desktop Client), add the file through your branch to the forked repo, sync the branch to the fork and then try for the pull request.

**Comment by RJP43** [comment]
Please note for us here any special aspects or difficulties you see while doing this. THANKS again :)

**Comment by brookestewart** [comment]
For reference: so far, I was able to clone the "new repo" to my local machine. However, it is still saying that I don't have permission to make any changes when I attempt to "publish" (sync). I had tried to sync my filed with the original repo first, and it said I didn't have permission. On my local machine, it looks as though my commit went through to the original, but it doesn't show up on the online version and doesn't allow me to erase it, and it still gives me the permission error when I try to sync, even without committing. I'm not sure if this is the reason it won't let me sync with the "new repo" or something else.

**Comment by nlottig94** [comment]
@RJP43    We, @ebeshero and I are trying the forking and branching.....are we doing this the right way?????

**Comment by nlottig94** [comment]
Help @RJP43 !!!!

**Comment by RJP43** [comment]
I am wondering should we have `<place>` for the general descriptions of where things are that aren't an exact address and have `<placeName>` only for full addresses. Ugh, today's class has me questioning our markup, again! Damn, @spadafour @nlottig94 @brookestewart.

**Comment by RJP43** [comment]
@nlottig94 Transcription of Article CSG 1888-08-12

**Comment by RJP43** [comment]
Thanks @brookestewart and @nlottig94 for the help transcribing early in the semester. Unfortunately there is a lot to review for article 8-10; therefore, it along with article 8-8 from last semester will sit outside of the data we mine this semester. However, we were able to update and review article 8-12 and we added it to the data for mining. Thanks again!
