### ISSUE TITLE
Help - edit Keystone DH proposal 

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls#38]
@ebeshero @ghbondar @nlottig94 @brookestewart @spadafour 

Hi everyone, 

I made a significant amount of edits to our [original Nelson conference proposal](https://github.com/RJP43/CitySlaveGirls/blob/master/Proposals_And_Papers/spadafour_2016_KeystoneDH.docx) (per @ebeshero 's suggestions) and now I am about 70 words over. If any of you could find the time to read over [this edited proposal](https://github.com/RJP43/CitySlaveGirls/blob/master/Proposals_And_Papers/parker_2016KeystoneDH.md) and suggest where is can be cut down or what needs further editing it would be greatly appreciated. Changes can be made to the file or commented on in this issue. Seeing as this needs done by Monday I would like to be done editing it by tomorrow. 

Thanks everyone!

**Comment by RJP43** [comment]
@ebeshero and @spadafour 

[Final Revisions](https://github.com/RJP43/CitySlaveGirls/blob/master/Proposals_And_Papers/parker_2016KeystoneDH.md) have been made to the proposal to get it down to 298 words. Could either of you please run through this and fix grammatical errors?

**Comment by ebeshero** [comment]
@RJP43 @spadafour I made a few small edits that I think ultimately trimmed it down by a few words. It looks exciting! Good work addressing the question of why this project matters in under 300 words!

**Comment by RJP43** [comment]
Thank you Dr. B!
