### ISSUE TITLE
ILiADS Conference

### ISSUE THREAD

**Issue by nlottig94** [RJP43/CitySlaveGirls#39]
@RJP43 @spadafour @brookestewart 
The proposal for this is due on Monday. I will try to get a proposal up by using what @spadafour and @RJP43 used for the Keystone Conference and the old proposal from @RJP43. I'll keep you up to date.

**Comment by nlottig94** [comment]
@RJP43 @spadafour @brookestewart 
Our proposal has been submitted via email to the ILiADS 2016 Steering Committee!!

**Comment by RJP43** [comment]
great thanks @nlottig94 !

**Comment by nlottig94** [comment]
@RJP43 @spadafour @brookestewart @ebeshero 
Our proposal to ILiADS has been accepted!!  We hadn't heard, so I emailed them this morning and got an email back saying that we were in and that a coach will be in touch with us shortly!!  The dates for the institute are July 24 through July 29 and will be held at Hamilton College in New York.  Registration begins on April 25, so we will have enough time to talk about where we want to stay in New York and how we will be getting there.  Follow [this link](http://iliads.org/) to get more info!

**Comment by ebeshero** [comment]
Huzzah!!!! And...wow!!!

**Comment by RJP43** [comment]
@nlottig94 I have been meaning to ask if we have any updates on this? And if not can you email him again or forward me his last message and I will email him? Thanks!

**Comment by nlottig94** [comment]
@RJP43 I just emailed him!  I Cc-ed you!  I'm sorry for the delay!

**Comment by nlottig94** [comment]
@RJP43 @brookestewart @spadafour 
Hi guys!!  So I hope you all got my text (even though I haven't heard back from any of you!!)! So here is the breakdown for ILiADS.

* They lowered the price from $850 per person to **$250 per person**!
* The cost to stay on campus is $50 per night per person.
Which means:
* $250 registration fee PLUS $250 for room and board = $500 per person total

We could get a hotel room which means:
* All four of us:
  * $176.91 for the room per person plus the $250 (so about $426.91 a person)
* If three of us go together:
  *  $219.27 per person for the room and the $250 (so about $469.27 a person)

Gas:
It's about 952 miles total (from my house, so it's a little more than for the rest of you, but just to get the the highest price). So my car gets around 36ish miles per gallon, which is about 26.44 gallons of gas at let's say $3 a gallon, which would be about $80 total for gas costs.

I have to get back to our coach _**as soon as possible**_, so I really need to hear back from you all!!

@ebeshero you can look at this too.

**Comment by RJP43** [comment]
Hey @brookestewart and @spadafour I am making plans with Nicole to attend this conference, but we need to know ASAP if you guys can join us. I understand $500-$600 is a lot of money to get together, but as we have discussed previously this is a fantastic opportunity not just in an academic sense or for the Nelson project but consider this as an experience that could potentially show future employers or grad schools your experience with digital scholarship. I think we have the opportunity here to pick up on a few programs and other digital tools we have yet to learn about and I for one would like to take advantage of that opportunity especially since they have discounted everything for us so graciously. 

Okay please let us know by tonight or have some kind of contact with one of us to let us know if you are considering and need more time. 

Thanks!!!

**Comment by RJP43** [comment]
An no pressure if you cant go that is fine, just please let us know!

**Comment by brookestewart** [comment]
I will be unable to attend due to money and schedule conflicts.

**Comment by nlottig94** [comment]
@RJP43 
I just registered for ILiADS!!! Just so you know, it was $250 for the registration and then it was $20 a night for student accommodation instead of $50!  So overall, it was $350, which cut off $150!!!  So all we'll have to worry about is the money for gas!!
@spadafour again, if you would like to go, let me know and I'll email you the link for the registration. _You should do this sooner rather than later_.
@brookestewart If you would like to change your mind, let me know!!

Hope you're all having a great summer!

**Comment by RJP43** [comment]
@nlottig94 @spadafour @brookestewart I am officially registered as well, and it was only $350!!! What a fantastic opportunity. There is still opportunity for either of you to register as well. Let me know if you need details :) can't wait for road trip to New York and a week of working on Nelson with several one on one meetings with "project experts"! Look forward to seeing you all at Keystone DH! Don't forget to register for that if you haven't already (let me know if you need the registration site for that as well).

**Comment by spadafour** [comment]
Hey guys, sorry I'm a little late to the party. I'm registered for the Keystone DH, but unfortunately, I won't be able to make it to the iliads conference.

**Comment by RJP43** [comment]
Thanks everyone for your responses. @nlottig94 and I have been in contact with our coach and plans are in the making for us to develop the reading interface and mapping. I am closing this issue and we will open a new issue during the conference to keep record of changes and issues as they arise.
