### ISSUE TITLE
Schematron Issue

### ISSUE THREAD

**Issue by nlottig94** [RJP43/CitySlaveGirls#53]
@RJP43 @spadafour I am currently transcribing the article Becca assigned me, and I noticed that since the GitHub was rearranged, there is an issue with the Schematron. I don't know if the file path needs changed?  I just wanted to let you guys know!

**Comment by RJP43** [comment]
@spadafour @nlottig94 @brookestewart If you are working on transcriptions just comment out the schematron line.. currently our schematron doe not align with everything that we are using in our code and it has been moved ... when these two things are fixed I will comment here with the correct schematron line.

Thanks!

**Comment by RJP43** [comment]
@nlottig94 @brookestewart @ebeshero 

@spadafour and I just finished updating our schematron! YAY! 

Any future transcriptions should associate the schematron by adding this line at the top of the document after the TEI schematron lines:

`<?xml-model href="../..//webDevelopment/nelsonSchematron.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>`

**Comment by RJP43** [comment]
I am closing this issue because I have added the correct schematron line to all of our transcribed files!
