### ISSUE TITLE
Project Orientation 

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls#7]
@KariWomack 
@spadafour 
@CodyKarch 
@rCarls 

Please refer to our very frst [Wiki](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/wiki/Welcome-New-Editors-to-The-Restoration-of-Nell-Nelson). 

I hope this helps each of you find your way around this repository. 

Any Questions post here!!

**Comment by RJP43** [comment]
@KariWomack A lot of the information we have right now in the file names will be moved into the TEI Headers of the individual files. In the meantime you can go forward with posting in *this issue* a systematic way of labeling the different source files so that we have shorter file and folder names. Don't make the changes just yet on the actual files because I still need to pull some of that information into the headers before it is gone and moved over to your better file naming system. Thanks.

**Comment by RJP43** [comment]
Great News!!! @abrennr completed the OCR of our third source. We will have to review the files and do regex to clean up the extra characters and general wonky-ness that comes in with OCR text. @KariWomack @spadafour @rCarls @CodyKarch  check out the new files [here](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/Anon_WhiteSlaveGirls_PDF) --- notice how for every .pdf file there is now a corresponding .txt file! You will want to consider our "new" source while developing TEI tags.

**Comment by ebeshero** [comment]
@RJP43 @KariWomack @ghbondar I just took part in a command-line "boot camp" here in Pittsburgh, working with Pittsburgh Supercomputer space--and I learned how to apply regular expression patterns to match on file names and change them in their file directories. So, based on what I learned, I know we can quickly change file names by matching on a particular pattern or series of characters (like we do with any regex matching), and we run some commands to loop through a directory to change those files in any way we designate. 

SO, think about regex or that consistent patterns we can remove in old file names: Can you identify some patterns?
And what simpler names will make the most functional and human-readable sense for the project?

**Comment by KariWomack** [comment]
Okay, exactly how many of these files need to be renamed? The reason I am asking is because I was wondering if certain things like tables and graphs would be part of other files, or if those need to also be systematically renamed on their own. Also, how do you feel about the commentary file names looking something like: NComm8-21 instead of Nell Nelson_8-21-1888_Commentary. Since all of the commentary files have the same year, al we need to make note of is the day and month, N for Nelson, and Comm for commentary. I also figured we could use the same for the articles but substitute Comm for Art. Comments?

**Comment by ebeshero** [comment]
So, I'm meeting with @RJP43 and @ghbondar now, and we're thinking maybe we want to keep the full date in case we want to add 1889 or 1890 articles later. But we can definitely shorten the names and that's a really good idea. I will suggest perhaps foregrounding the newspaper title in the filename as a standard way to put forward the publication medium: Eventually you may be adding articles from OTHER newspapers (say the New York World), so you want to be able to tell instantly what the source is from the file name, just to make your project development life a little easier! 

Think about sorting the files by year in the file directory:

1888-01-25-ChTimes.xml

1890-07-29-NYWorld.xml

We profs recommend changing the PDF file names to match, so you can instantly correlate them.

**Comment by ebeshero** [comment]
Book publications: keep it simple? Try for the books:

BarkleyS01
BarkelyS02
BarkleyS03
...
BarkelyS10
BarkelyS11
etc
(The Barkley pub isn't divided into chapters, and has more than 10 sections. Make your numbering go:
01 ... 10...20...30 so they can be sorted.)


VS.

McEnnisC01
McEnnisC02
McEnnisC03
...
McEnnisC39

**Comment by RJP43** [comment]
In order to get credit for participation in last week's and this week's project development I would like each of you @spadafour @rCarls @CodyKarch @KariWomack to read one article from the PDF images of the original articles and try your hand at transcribing it. In oXygen open a new XML document and give the document a root element of  `div type="article"` be sure to leave a comment tag or feel free to begin creating a basic TEI header with the publication date included inside. Separate the headlines from the main body of the article with `div` elements setting the attributes to `@type="headlines"` and `@type="body". Use the self-closing `<gap/>` element and either a comment tag or logical attribute to indicate words that are difficult to transcribe and reason why. Separate parahraphs with the `<p>` elements and if advertisements for future newspaper issues related to the Nelson series follow the main body of the article separate those into a separate `<div type="advertisement">`. Mark with comments areas of interest and parts of the article that stand out to you and then push your finished transcription to the [OriginalArticle_XML Folder](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/OriginalArticles_XML) using your desktop client. Once you have completed your transcription (not an easy task so give yourself sufficient time) go into the [Anon.WhiteSlaveGirls Folder](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/Anon_WhiteSlaveGirls_PDF) and hunt for the corresponding Barkley Section (you can best do this by skimming the headlines of the sections in search of headlines that match those from your article). Review your section in comparison with you article and jot down any noticeable differences. Once you have completed all of these tasks comment in [Issue 9](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/issues/9) giving us which section from the Barkley text a.k.a. Anon.WhiteSlaveGirls corresponds with the article you transcribed. This will be significant project work helping transcribe, begin basic TEI structure tagging, and versioning. This will also give each of you a chance to become better associated with the Nelson project and begin the process of finding interesting things each of you may want to produce data visualizations on for upcoming assignments. 

Article Assignments:
@spadafour --- [8/6/1888](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/OriginalArticles_PDF/Nell_Nelson_8-6-1888.pdf)
@rCarls --- [8/7/1888](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/OriginalArticles_PDF/Nell_Nelson_8-7-1888.pdf)
@CodyKarch --- [8/8/1888](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/OriginalArticles_PDF/Nell_Nelson_8-8-1888.pdf)
@KariWomack --- [8/9/1888](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/OriginalArticles_PDF/Nell_Nelson_8-9-1888.pdf)

Please contact me via email or in this issue with any questions and concerns as they arise. 
Thank you!

**Comment by RJP43** [comment]
I am going to make a new issue better directing how to complete the tasks laid out in the above comment!
